export function handleException(status) {
    alert('error : ' + status);
}